#A)
print("Hola Mundo")
#B)
name=input("ingrese su nombre: ")
print(f"Hola {name} como andas?")
#C)
num1=int(input("ingrese el num1: "))
num2=int(input("ingrese el num2: "))
print(f"La suma es {num1+num2} y la resta es {num1-num2}")
#D)
a=int(input("Ingrese el num1: "))
b=int(input("Ingrese el num2: "))
c=int(input("Ingrese el num3: "))
print(f"La suma es {a+b+c} y el promedio es {(a+b+c)/3}")
#E)
monto=int(input("Ingrese el monto de una factura"))
print(f"El iva (21%) es de {monto*.21}")